### PR TITLE
Refresh the sessionId if the apiKey changed in the config.

### PR DESCRIPTION
**Pull request by Natim**
https://bugzilla.mozilla.org/show_bug.cgi?id=1266087

### CODE REVIEW

**Comment by leplatrem** [comment]
r+

**Comment by Standard8** [comment]
Shouldn't we also be storing the apiKey when we initially create the room?

**Comment by Standard8** [comment]
> Shouldn't we also be storing the apiKey when we initially create the room?

Ah, we seem to be doing that already here:

https://github.com/mozilla-services/loop-server/blob/34631f4dcc6f9f92b64962ad5fc1ce71e8936daf/loop/routes/rooms.js#L208

In which case, the changes look good.

**Comment by Natim** [comment]
Thanks for your feedback and review.

**Pull request merged**
