### PR TITLE
Add a new __lbhealthcheck__ endpoint.

### PR DESCRIPTION
**Pull request by Natim**
https://bugzilla.mozilla.org/show_bug.cgi?id=1253257

### CODE REVIEW

**Comment by leplatrem** [comment]
r+

**Comment by Natim** [comment]
@Micheletto @mostlygeek I am merging so that I can release 0.19.4 on it. But feel free to give me feedback and tell me if it fits your need and we can iterate.

**Comment by mostlygeek** [comment]
R+.

Doesn't have to be a json response, only HTTP 200 is required.

**Comment by Micheletto** [comment]
LGTM

**Pull request merged**
