### PR TITLE
Add an option to bypass the redis pubsub config

### PR DESCRIPTION
**Pull request by almet**

### CODE REVIEW

**Comment by ametaireau** [comment]
This needs a test.

**Comment by Natim** [comment]
Is this still needed?

**Comment by ametaireau** [comment]
Yes. it's to avoid sending the option to the redis on prod which are already configured with it (plus amazon doesn't care about these options and will answer that the config command doesn't exist).

**Comment by Natim** [comment]
Then we should fix it :)

**Pull request closed without merging**
